Sprint 2
Simaleon/middle.messenger.praktikum.yandex pull request #3
Opened 2022-07-13 21:19 UTC by Simaleon

2022-07-14 09:27 UTC, podlovchenko requested changes
Привет, спасибо за выполненную работу!)
Есть несколько замечаний:
1. Много где используется тип `any`, это не очень хорошая практика, так как теряются преимущества типизирования, попробуй заменить на подходящие типы
2. Нет валидации данных на странице редактирования профиля
3. По ссылке на нетлифай ничего не открывается 
4. При запуске `npm run stylelint` `When linting something other than CSS, you should install an appropriate syntax, e.g. "postcss-less", and use the "customSyntax" option`

2022-07-14 09:27 UTC, podlovchenko commented on src/HTTPTransport.ts
> +    return str.substring(1);
Можно использовать метод reduce для Object.entries(data)

2022-07-14 18:03 UTC, Simaleon commented on src/pages_templates/chat/ChatModel.ts
> +    ]
С большой вероятностью тип поменяется уже в следующем спринте

2022-07-15 06:23 UTC, podlovchenko commented on src/HTTPTransport.ts
> +}
Да, конечно, просто рассказываю о наиболее часто используемом варианте, в документации https://www.typescriptlang.org/docs/handbook/enums.html#handbook-content

2022-07-15 06:36 UTC, podlovchenko commented
Работу принимаю)

2022-07-16 15:15 UTC, merged